### ISSUE TITLE
A few improvements on Edge support

### ISSUE THREAD

**Issue by lminiero** [fippo/adapter#2] opened 2015-10-15 11:17 UTC
Hi,

as anticipated on Twitter, I've been playing a bit with Edge support in order to get it working with Janus. On the client side we mostly use a slightly older version of adapter.js, so it made sense to try and incorporate the code you wrote some time ago (bundle-edge.js) in there in order to expose Edge support too. It wasn't all roses, mostly because of the obscure error reporting on the Edge JavaScript developer console (which I guess is reasonable, considering the experimental nature of the new features), but eventually I mostly got it working.

I know you said a lot has changed since that version I based on (I can see that on the code here, great job!), but I thought I'd share some of the things I found out as they may be helpful in improving the current version of the shim too.

Besides some additions that are not really relevant, I had to fix a few things in the original code to get it working with Edge in my scenario, which as was always using Janus as the peer:
1. I had to comment out the `'use strict';` part, as Edge was complaining with a "variable undefined in strict mode" when setting `webrtcMinimumVersion`.
2. Not sure if it's an issue with Edge or not, but whatever `iceServers` I passed I got an exception; some more details can be found [here](https://connect.microsoft.com/IE/feedbackdetail/view/1894505/rtcicegatherer-rtcicetransport-issues), on the Connect issue I opened; anyway, I had to force an empty array as `iceServers` as the only way to go on, thus skipping what you do [here](https://github.com/fippo/adapter/blob/shim-ortc/adapter.js#L927).
3. Your original code only added candidates received via trickling, but ignored any candidate that may be available in the SDP, thus preventing support for half-trickle. At the moment, Janus always advertizes its own candidates in the SDP (while browsers themselves can trickle), so I added a very simple filter to also parse candidates in there. The way I did this is pretty crude, right now, and you can find it [here](https://github.com/meetecho/janus-gateway/blob/janus-edge/html/adapter.js#L869); the idea is to parse candidates, add them to an array, and then pass them one by one to `addIceCandidate` when needed (SLD or SRD). It's quite crude as it doesn't work well when remote candidates are both in the SDP and trickles, as the way I did it now always adds an `endOfCandidates` after the remote candidates parsed in the SDP, which is not what it should do, but it does the job in my case.
4. I modified `_getCommonCapabilities` so that the name matching would be done on the `toLowerCase` version of the codec name, rather than the name itself. In fact, in my tests this was failing when negotiating audio as the "OPUS" Edge used didn't match the "opus" Janus negotiated. I checked and it still is an issue in your [latest version](https://github.com/fippo/adapter/blob/shim-ortc/adapter.js#L977) too.
5. I had to add a further check in `_getRemoteCapabilities`, in particular when parsing codecs in the SDP in order to add them to the list of codecs the peer supports. Parsing works fine, but when passing them to Edge it would cause exceptions for codecs it didn't know about. For instance, in some of my tests I used the SIP gateway feature in Janus, which resulted in the peer advertizing supports for stuff like GSM, speex, telephone-event, etc. which confused Edge: I can't recall where this happened exactly, I think when doing `rtpReceiver.receive(params);` after getting the common capabilities, which should have already filtered them out. I tried selectively removing the non-WebRTC codecs one by one, but I always got the exception: the only way to get that working was to filter them all out in `_getRemoteCapabilities` as done [here](https://github.com/meetecho/janus-gateway/blob/janus-edge/html/adapter.js#L469). A very ugly hack, but until this is fixed in Edge there's no prettier way of doing that.

I think that's all. I have some more notes but, again, it's mostly on some things I have to move around a bit to make it work with the adapter version I had, and so may be more confusing than helpful. Let me know if there's any other detail I can provide you with, or if there's any way I can help you improving the code you already have in place now.

Thanks!

**Comment by fippo** [comment] 2015-10-21 03:37
hey Lorenzo,

thanks for the feedback and sorry for the delay.
(1) odd, not an issue on any sites i've tried. Do you have a url where I can try to repro?
(2) known issue (but I forgot to comment that). This should have been fixed in early October but is AFAIK not yet in build 10565. I'll check and get your issue updated. What works is a turn: url with port and transport attributes, i.e. turn:host:3478?transport=udp
(3) should be easier with the new SDPUtils module. Do you include a=end-of-candidates in the SDP? Then it would be possible to use setRemoteCandidates.
(4) fixed in https://github.com/fippo/adapter/commit/5a111f8c60d862287d4e0a1088b558974732cabd, will report upstream as well.
(5) sounds familiar, Edge doesn't like unknown codecs (and it's probably correct spec-wise). Do you have an example of the SDP and the resulting common caps? (and I need to check if I have a regression here in the lastest version... thanks!).

**Comment by lminiero** [comment] 2015-10-21 13:39
Hi Philipp,

no problem at all, we're all awfully busy! :smile: 

About (1), you can see the difference on these two links here:

* https://janus.conf.meetecho.com/echotest uses the version of the adapter with the "strict" line commented out;
* https://janus.conf.meetecho.com/echotest-strict instead makes use of it; in my Edge, the first works while the 2nd fails at the beginning as shown on the console; if this is working as expected in your new code (which I didn't have the time to test yet, sorry about that), this may be a consequence of my integration of the bundle-edge.js code within the old adapter, and so my mistake somewhere.

As to (3), I'm not including an a=end-of-candidates attribute: the only thing I do when parsing is storing candidates in the array. Then, in either SLD or SRD I traverse the array and use addIceCandidate for all of them, followed at this point by an end-of-candidates to complete the setup. That's why in hybrid scenarios (e.g., peer sending a couple of host candidates in the SDP, followed by trickles later on) this may cause issues.

Finally, for what concerns (5), I checked the code again and the issue in ```bundle-edge.js``` is that ```setRemoteDescription``` uses the ```remoteCapabilities``` directly instead of ```commonCapabilities``` when handling an answer. You can check this [here](https://simplewebrtc.com/bundle-edge.js), in ```window.RTCPeerConnection.prototype.setRemoteDescription =```, in the ```if (description.type === 'answer') {``` branch: you'll see that ```rtpReceiver.receive(params, kind);``` is done on a ```params = remoteCapabilities;``` from a few lines before. Not sure if this is still an issue in your updated adapter.js, but I guess it's been fixed as it looks the ```rtpReceiver.receive``` code is now in ```window.RTCPeerConnection.prototype._transceive``` which always seems to take care of the capabilities in the right way.

Hope this helps!

**Comment by fippo** [comment] 2015-10-23 04:44
(1) looks like your'e missing some upstream changes from adapter in the strict version, it also doesn't have the webrtcUtils.log stuff. The variable should have been defined along with webrtcDetectedBrowser et al.

(3) instead of an array you could use http://ortc.org/wp-content/uploads/2015/06/ortc.html#widl-RTCIceTransport-setRemoteCandidates-void-sequence-RTCIceCandidate--remoteCandidates -- this basically adds an array of candidates and implies end-of-candidates. Will not work in mixed scenarios where some candidates are trickled and some are not however -- end-of-candidates in the SDP would allow detecting what needs to be used. Hm...

(5) I think I understand what's going on... I assumed that the answer was always going to be a subset of the offer. Which 3264 doesn't guarantee. Bug indeed but if the new version fixes it...

Looks like the stun fix won't make it, will add a workaround.

**Comment by lminiero** [comment] 2015-10-23 08:26
> (1) looks like your'e missing some upstream changes from adapter in the strict version, it also doesn't have the webrtcUtils.log stuff. The variable should have been defined along with webrtcDetectedBrowser et al.

Yep, I think I've been lazy on that part and we're still relying on an older version. I'll make sure I'll update this as soon as your PR ends in mainstream!

> (3) instead of an array you could use http://ortc.org/wp-content/uploads/2015/06/ortc.html#widl-RTCIceTransport-setRemoteCandidates-void-sequence-RTCIceCandidate--remoteCandidates -- this basically adds an array of candidates and implies end-of-candidates. Will not work in mixed scenarios where some candidates are trickled and some are not however -- end-of-candidates in the SDP would allow detecting what needs to be used. Hm...

That's true, although this would require applications to adhere to this syntax/specification for this to work in the general case. On one side I think maybe this should to be standardized, e.g., as part of the ongoing efforts on trickle or as a separate document. On the other side, if the peer says it's trickling, but then sends all its candidates in the SDP (so actually half-trickle), then it's the peer responsibility to say candidates are over in an out-of-band message, as it would do for regular trickle updates.

> (5) I think I understand what's going on... I assumed that the answer was always going to be a subset of the offer. Which 3264 doesn't guarantee. Bug indeed but if the new version fixes it...

Yes, I don't think you need to worry about that.

> Looks like the stun fix won't make it, will add a workaround.

Cool! Is there any channel where MS developers are advertizing these updates and discussing these issurs? I couldn't find any, and the issue page I opened on their Connect tracker has been ignored so far.

**Comment by fippo** [comment] 2017-03-05 11:01
I think this is mostly done, holler if wrong

**Closed by fippo** 2017-03-05 11:01 UTC
